# Generated by Django 6.0.2 on 2026-03-02 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_stockmovement_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmovement',
            name='purchase_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
