# Generated by Django 6.0.2 on 2026-03-03 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_alter_product_min_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='min_stock',
        ),
    ]
