# Generated by Django 6.0.2 on 2026-03-15 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_salesreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmovement',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
